# A TOML plugin for proto:
# https://moonrepo.dev/docs/proto/plugins#toml-plugin

name = "flux"
type = "cli"

[platform.macos]
download-file = "flux_{version}_darwin_{arch}.tar.gz"
checksum-file = "flux_{version}_checksums.txt"

[platform.linux]
download-file = "flux_{version}_linux_{arch}.tar.gz"
checksum-file = "flux_{version}_checksums.txt"

[platform.windows]
download-file = "flux_{version}_windows_{arch}.zip"
checksum-file = "flux_{version}_checksums.txt"

[install]
download-url = "https://github.com/fluxcd/flux2/releases/download/v{version}/{download_file}"
checksum-url = "https://github.com/fluxcd/flux2/releases/download/v{version}/{checksum_file}"

[install.arch]
aarch64 = "arm64"
x86_64 = "amd64"

[resolve]
git-url = "https://github.com/fluxcd/flux2"
